import Head from "next/head";

interface SiteHeadProps {
	title: string;
}

const SiteHead = ({ title }: SiteHeadProps) => {
	return (
		<Head>
			<title>{title} | Gestion Locative</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
};

export default SiteHead;
