version: "3.3"

services:
    backend:
        image: gestion-locative-backend
        build:
            context: ..
            dockerfile: docker/backend.dockerfile
        ports:
            - "1234:1234"

    frontend:
        image: gestion-locative-frontend
        build:
            context: ..
            dockerfile: docker/frontend.dockerfile
        ports:
            - "80:80"
